name:                void-space
version:             0.1.0.0
github:              "ChrisPenner/void-space"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/void-space#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty
- containers
- mtl
- lens
- text
- random
- streams
- finite-typelits
- word-wrap

library:
  source-dirs: src
  default-extensions: 
    - StrictData
    - TypeApplications
    - DataKinds
    - ViewPatterns
    - FlexibleInstances
    - FlexibleContexts
    - DeriveFunctor
    - DeriveTraversable

executables:
  void-space-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - void-space
    - streams
    - async

tests:
  void-space-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - void-space
